### ISSUE TITLE
Rentry and os error

### ISSUE THREAD

**Issue by BridgeKeeper1** [Hawkish-Team/Hawkish-Grabber#11]
https://rentry.co/shitonyourAV/raw does not work and i get this error

Traceback (most recent call last):                                                                                        File "C:\Users\TEST\Downloads\Hawkish-Grabber-main\Hawkish-Grabber-main\test.py", line 2653, in <module>           asyncio.run(hwkish_first_funct().init())                                                                              File "C:\Users\TEST\Downloads\Hawkish-Grabber-main\Hawkish-Grabber-main\test.py", line 680, in __init__            self.chrome_key = self.mykey_gtm(                                                                                     File "C:\Users\TEST\Downloads\Hawkish-Grabber-main\Hawkish-Grabber-main\test.py", line 192, in mykey_gtm           with open(path, "r", encoding="utf-8") as f:                                                                        OSError: [Errno 22] Invalid argument: 'C:\\Users\\TEST\\AppData\\Local\\Google\\Chrome\\<!DOCTYPE html>\n<html>\n\n<head>\n    <meta charset="utf-8">\n    \n<title>Error</title>\n\n    \n    <meta name="description" content="Markdown pastebin service with preview, custom urls and editing. Fast, simple and free.">\n    <meta name="keywords" content="pastebin, markdown, publishing, markdown pastebin, markdown from command line">\n\n    <meta name="twitter:card" content="summary" />\n    <meta name="twitter:description" content="Markdown pastebin service with preview, custom urls and editing." />\n    <meta name="twitter:title" content="Rentry.co - Markdown Pastebin" />\n    <meta name="twitter:site" content="@rentry_co" />\n    <meta name="twitter:image" content="https://rentry.co/static/icons/512.png" />\n\n    <meta property="og:url" content="https://rentry.co/" />\n    <meta property="og:title" content="Rentry.co - Markdown Pastebin" />\n    <meta property="og:description" content="Markdown pastebin service with preview, custom urls and editing." />\n    <meta property="og:image" content="https://rentry.co/static/icons/270.png" />\n    <meta property="og:type" content="website" />\n    \n    <meta name="referrer" content="strict-origin-when-cross-origin" />\n    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=1" />\n\n    <link rel="stylesheet" href="/static/css/bootstrap.min.css?v=84">\n    <link rel="manifest" href="/static/manifest.json?v=8">\n    <script>document.documentElement.classList.toggle("dark-mode", (localStorage.getItem("dark-mode") === null && window.matchMedia("(prefers-color-scheme: dark)").matches || localStorage.getItem("dark-mode") == "true"));</script>\n    <script>const script = document.createElement("script"); const hn = window.location.hostname === \'rentry.org\' && \'rentry.org\' || \'rentry.co\'; script.src = \'https://a.\' + hn + \'/js/plausible.js\'; script.defer = true; script.setAttribute(\'data-domain\', hn + \',rentry\'); document.head.appendChild(script);</script>\n</head>\n\n<body class="m-0 p-0">\n\n    <div class="container container-smooth">\n        <div class="row no-gutters">\n            \n<div class="col-12">\n    <div class="row no-gutters">\n        <div class="p-2 my-5 mx-auto text-center">\n            <h1 class="h4 text-gray-dark my-3 no-pointer">Error</h1>\n            <span class="h5 text-gray-dark font-weight-normal m-0">404 not found</span>\n        </div>\n    </div>\n</div>\n\n\n\n            \n            <div class="text-center w-100 mb-3">\n                <hr class="my-2 basement-hr">\n                <a class="mr-1" href="/">new</a>&middot;<a class="mx-1" href="/what">what</a>&middot;<a class="mx-1" href="/how">how</a>&middot;<a class="mx-1" href="/langs">langs</a>&middot;<a class="ml-1" href="/what#contacts">contacts</a>\n<div class="position-relative"><span style="right: 0; bottom: -9px; background:transparent!important" class="position-absolute btn squared mr-2 mr-sm-0" id="darkModeBtn" title="Dark/light mode"></span></div>\n\n            </div>\n            \n            \n        </div>\n    </div>\n\n    <script src="/static/js/jquery.min.js?v=20"></script>\n    <script src="/static/js/bootstrap.min.js?v=20"></script>\n    \n</body>\n\n</html>\n\\Local State'

**Comment by Hawkishx** [comment]
patched!
